name: Test Snapshot Storage

on:
  workflow_dispatch:  # Allow manual trigger for testing
  pull_request:
    paths:
      - 'src/storage/**'
      - 'tests/storage/**'
      - '.github/workflows/test-snapshot.yml'

jobs:
  test-snapshot-unit:
    name: Snapshot Storage Unit Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run snapshot format tests
      run: npx jest tests/storage/snapshot-format.spec.ts --runInBand --verbose
      env:
        NODE_ENV: test

    - name: Run PulsarStorage unit tests with mocks
      run: npx jest tests/storage/pulsar-storage.spec.ts --runInBand --verbose
      env:
        NODE_ENV: test
        STORAGE_TYPE: pulsar
        SNAPSHOT_INTERVAL: 30

  test-snapshot-integration:
    name: Snapshot Storage Integration Tests
    runs-on: ubuntu-latest
    # Only run if we have secrets configured
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository)
    
    services:
      # Mock S3 service for testing
      minio:
        image: minio/minio:latest
        ports:
          - 9000:9000
        env:
          MINIO_ROOT_USER: minioadmin
          MINIO_ROOT_PASSWORD: minioadmin
        options: --health-cmd "curl -f http://localhost:9000/minio/health/live" --health-interval 10s --health-timeout 5s --health-retries 5
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Setup MinIO bucket
      run: |
        npm install -g minio-client-cli
        mc alias set myminio http://localhost:9000 minioadmin minioadmin
        mc mb myminio/test-bucket || true

    - name: Run snapshot integration tests
      run: |
        # Export MinIO credentials for S3 compatibility
        export S3_ACCESS_KEY_ID=minioadmin
        export S3_SECRET_ACCESS_KEY=minioadmin
        export S3_ENDPOINT=http://localhost:9000
        export S3_BUCKET=test-bucket
        export STORAGE_TYPE=pulsar
        export SNAPSHOT_INTERVAL=10
        
        # Run tests that don't require real Pulsar
        npx jest tests/storage/pulsar-storage.spec.ts --runInBand --verbose
      env:
        NODE_ENV: test

  validate-build:
    name: Validate TypeScript Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: TypeScript check
      run: npx tsc --noEmit

    - name: Build project
      run: npm run build

    - name: Verify snapshot exports
      run: |
        # Check that DocumentSnapshot interface is exported
        grep -q "export interface DocumentSnapshot" src/storage/pulsar-storage.ts || exit 1
        echo "✅ DocumentSnapshot interface is properly exported"